package munkle::Model::MunkleModel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MunkleSchema',
    
    connect_info => {
        dsn => 'dbi:mysql:munkle',
        user => 'root',
        password => '',
    }
);

=head1 NAME

munkle::Model::MunkleModel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<munkle>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MunkleSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
